# Generated by Django 5.0.1 on 2024-06-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='Image',
        ),
    ]
